title: فیلم‌خانه
description: > # this means to ignore newlines until "baseurl:"
  معرفی فیلم
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://video.mhkarami97.ir" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: mhkarami97 #if your site has a twitter account, enter it here

# Author Settings
author: Mohammad Hossein Karami # add your name
author-img: my.jpg # add your photo
# about-author: یک برنامه نویس # add description
social-email: mhkarami97@gmail.com # add your Email address

# Disqus
# discus-identifier: mhkarami97 # add your discus identifier

# Tracker
google_analytics: "G-2KGKGYQR60"
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-2KGKGYQR60"
    anonymize_ip: false # default

comments:
   provider: ""

giscus:
  repo: "MHKarami97/video"
  repo-id: "MDEwOlJlcG9zaXRvcnkzNTA2MjIxNDc="
  category: "General"
  category-id: "DIC_kwDOFOYRw84B-Ro_"
  mapping: "pathname"
  reaction-enabled: "1"
  theme: "light"
  crossorigin: "anonymous"

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 15
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
